### PR TITLE
Implements keysSet

### LINKED ISSUE #47: Should we have a `keysSet` function?
`keysSet :: forall k v. Map k v -> Set k`

See the Haskell equivalent: https://hackage.haskell.org/package/containers-0.5.11.0/docs/Data-Map-Lazy.html#v:keysSet

### PR DESCRIPTION
**Pull request by kritzcreek**
Fixes #47

### CODE REVIEW

**Comment by hdgarrood** [comment]
It’s a bit odd to have this here as opposed to in `maps`, I think.

**Comment by kRITZCREEK** [comment]
@hdgarrood sets depends on map, so it can't be in maps

**Comment by hdgarrood** [comment]
Right, sorry, I’m aware of that. I mean from the perspective of what API makes sense. I’m saying, perhaps we should consider reorganising things.

**Comment by kRITZCREEK** [comment]
I see, yeah I could see an `ordered-containers` package which contains all the structures depending on the ordered trie.

**Comment by hdgarrood** [comment]
See also #46. I think it makes sense to at least put maps and sets together, especially in light of this.

**Pull request closed without merging**
