### PR TITLE
Added subset, properSubset, and intersection.

### PR DESCRIPTION
**Pull request by pseudonom**

### CODE REVIEW

**Comment by paf31** [comment]
@garyb What do you think -

a) Move the `transformers` `MonadRec` instances into `transformers` or
b) Adding a `transformers` dependency here.

?

I think I'd prefer a)

**Comment by garyb** [comment]
So in *a* `transformers` would depend on `tailrec`? Sounds good to me.

**Comment by paf31** [comment]
Yep.

**Comment by garyb** [comment]
That's not too huge of a breaking change either:

- purescript-lists
- purescript-free
- purescript-angular
- purescript-strongcheck
- purescript-argonaut
- purescript-base
- purescript-mongodbf
- purescript-task
- purescript-streams

**Comment by paf31** [comment]
Well `transformers` doesn't need a major version bump, just `tailrec` (and `free`) right?

**Comment by garyb** [comment]
I guess not, as anything that pulls in `tailrec` already has `transformers` so swapping the order of dependency shouldn't break anything else. That gives us:

- purescript-free
- purescript-angular
- purescript-strongcheck
- purescript-argonaut
- purescript-base
- purescript-mongodbf

**Comment by pseudonom** [comment]
Bump

**Comment by garyb** [comment]
Can you rebase and update please? Sorry this went unmerged, things for 0.7 took so much longer than we expected and only just catching up with the outstanding PRs and issues now!

**Comment by garyb** [comment]
Closing as @hdgarrood fixed it up as #28

**Pull request closed without merging**
