### PR TITLE
Added Foldable instance

### PR DESCRIPTION
**Pull request by zudov**

### CODE REVIEW

**Comment by garyb** [comment]
:+1: although I wonder if there's a better way than converting to list first. @paf31?

**Comment by zudov** [comment]
@garyb I've been thinking of better way. It would involve adding something like `Data.Map.foldWithKey`. But then I've taken a look at `Data.Map` and found out that it also basically converts the thing to the list (by taking `Map.values`) and runs `fold` on that list.

**Comment by garyb** [comment]
Ah ok, cool. I'll let @paf31 merge this anyway, as it's more his baby :smile:

**Comment by paf31** [comment]
:+1: Thanks. We can come back to `foldWithKey` if necessary.

**Comment by zudov** [comment]
@paf31 From brief look into `purescript-{maps,sets}` it seemed to me that there was no focus on performance. If I understand correctly it's just 'good enough' at the moment, and the code can be kept much simpler. Right?

**Comment by paf31** [comment]
Yeah I think so, although I'd be happy to improve things if someone wanted to improve them :)

**Pull request merged**
